services:
  db:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: the-wedding-game-api
      POSTGRES_PASSWORD: abcd@123
      POSTGRES_DB: the-wedding-game