services:
  db:
    container_name: the-wedding-game-db-test
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: the-wedding-game-api
      POSTGRES_PASSWORD: abcd@123
      POSTGRES_DB: the-wedding-game

  s3-ninja:
    container_name: the-wedding-game-s3ninja-test
    image: scireum/s3-ninja:latest
    ports:
      - "127.0.0.1:9444:9000"