name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
      branches:
          - main
  workflow_dispatch:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup Go
            uses: actions/setup-go@v2
            with:
              go-version: 1.23
              cache-dependency-path: subdir/go.sum

          - name: Install dependencies
            run: go mod download

          - name: Build project
            run: go build -v ./...

          - name: Run tests
            run: go test -v ./... -cover -coverprofile=coverage.txt

          - name: Upload coverage reports to Codecov
            uses: codecov/codecov-action@v5
            with:
              token: ${{ secrets.CODECOV_TOKEN }}
              slug: the-wedding-game/the-wedding-game-api
