name: Continuous Delivery

on:
  push:
      branches:
          - main
  workflow_dispatch:

jobs:
    push-to-registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
          packages: write
          contents: read
          attestations: write
          id-token: write

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build and push Docker image
            id: push
            uses: docker/build-push-action@v6
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: kaneeldias/the-wedding-game-api:${{ github.sha }}
